[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts'
]
[invariant]
runs = 2 #WSL Can't handle this properly fast :(
depth = 128
fail_on_revert = true
# ffi = true
# fs_permissions = [
#     { access = "read", path = "./img/" },
#     { access = "read", path = "./broadcast" },
# ]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
